# Flat over flat surface configuration

[geometry]
[geometry.grid]
pixel_size = 0.1
nb_pixels = 256

[geometry.upper]
shape = "flat"
constant = 0.0

[geometry.lower]
shape = "flat"
constant = 0.0

[physics]
[physics.capillary]
interface_thickness = 0.1
contact_angle_degree = 90.573
liquid_volume_percent = 50.0

[simulation]
[simulation.trajectory]
min_separation = 0.2
max_separation = 0.3
step_size = 0.02

[simulation.solver]
max_nb_iters = 1000
max_nb_loops = 30
tol_convergence = 1e-6
tol_constraints = 1e-8
init_penalty_weight = 0.1
