# Sinusoid over flat surface configuration (hydrophilic)
# All length scale values, the unit is 100nm = 0.1microns

[domain]
[domain.grid]
pixel_size = 0.05
nb_pixels = 256

[physics]
[physics.upper]
shape = "sinusoid"
wavenumber = 4.0
amplitude = 0.2

[physics.lower]
shape = "flat"
constant = 0.0

[physics.capillary]
# It seems when this value is smaller than pixel_size,
# it can converge to less optimal or even weird patterns
interface_thickness = 0.05
contact_angle_degree = 45.0
liquid_volume_percent = 25.0

[numerics]
[numerics.solver]
max_nb_iters = 1000
max_nb_loops = 50
tol_convergence = 1e-8
tol_constraints = 1e-8
init_penalty_weight = 0.1

[simulation]
[simulation.trajectory]
# FIXME: on "approaching", it can trigger "ABNORMAL" at certain positions.
min_separation = 0.0
max_separation = 0.1
step_size = 0.01
