# Tip over sinusoid surface configuration (hydrophobic)
# Contact angle > 90 degrees

[geometry]
[geometry.grid]
pixel_size = 0.05
nb_pixels = 256

[geometry.upper]
shape = "tip"
# For big tip, radius should be larger than 1.415 of domain size
# to eliminate corner effects
radius = 10.0

[geometry.lower]
shape = "sinusoid"
wavenumber = 10.0
amplitude = 0.2

[physics]
[physics.capillary]
interface_thickness = 0.05
contact_angle_degree = 135.0
liquid_volume_percent = 85.0

[simulation]
[simulation.trajectory]
min_separation = 0.0
max_separation = 0.1
step_size = 0.01

[simulation.solver]
max_nb_iters = 1000
max_nb_loops = 30
tol_convergence = 1e-6
tol_constraints = 1e-8
init_penalty_weight = 0.1
